---
- name: Add Ubuntu Repo Key
  apt_key:
    keyserver: 'hkp://keyserver.ubuntu.com:80'
    id: EA312927
    state: present
  when:
    - ansible_os_distribution == 'Ubuntu'

- name: Add Ubuntu Repo
  apt_repository:
    repo: 'deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse'
    state: present
    update_cache: yes
  when:
    - ansible_os_distribution == 'Ubuntu'

- name: Install MongoDB
  apt:
    name: 'mongodb-org'
    state: present
  when:
    - ansible_os_distribution == 'Ubuntu'
