---
- name: Install required packages
  apt:
    name: '{{ item }}'
    state: present
  with_items:
  - curl
  - openssh-server
  - ca-certificates
  - postfix
  - apt-transport-https

- name: Add GitLab Repository
  apt_repository:
    filename: gitlab-latest
    repo: 'deb https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/ trusty main'
    state: present

- name: Install GitLab
  apt:
    name: gitlab-ce
    state: present
