---
- name: Configure default PHPMyAdmin settings
  shell: 'echo "phpmyadmin phpmyadmin/reconfigure-webserver multiselect nginx" | debconf-set-selections'

- name: Install PHPMyAdmin
  apt:
    name: phpmyadmin
    state: present

- name: Include Debian Vars
  include_vars: Debian.yml
