---
- include: install_debian.yml
  when: (ansible_os_family == 'Debian') and (phpmyadmin_install = 'Yes')

- include: install_redhat.yml
  when: (ansible_os_family == 'RedHat') and (phpmyadmin_install = 'Yes')

- include: configure_redhat.yml
  when: (ansible_os_family == 'RedHat') and (phpmyadmin_install = 'Yes')

- include: configure_common.yml
  when: phpmyadmin_install = 'Yes'

