---
- name: Install NPM
  apt:
    name: npm
    state: present

- name: Install 'n'
  shell:
    'npm install -g n'

- name: Install the latest stable version of NodeJS
  shell:
    'n stable'

- name: Get the version of NodeJS that was installed
  shell:
    'n --stable'
  register: parse_node_version

- name: Create Symlinks for NodeJS
  file:
    src: '/usr/local/n/versions/node/{{ parse_node_version }}/bin/node'
    path: '/usr/local/bin/{{ item }}'
    state: link
  with_items:
    - 'node'
    - 'nodejs'

- name: Create Symlink for NPM
  file:
    src: '/usr/local/n/versions/node/{{ parse_node_version }}/bin/npm'
    path: '/usr/local/bin/npm'
    state: link
    
- name: Install NPM packages
  shell:
    'npm install -g {{ item }}'
  with_items: '{{ parse_npm_pkgs }}'
