---
- name: Download Composer Installer
  get_url:
    url: 'https://getcomposer.org/installer'
    dest: '/tmp/composer'

- name: Install Composer
  shell: 'cat /tmp/composer | php'
  args:
    chdir: '/tmp'

- name: Move Composer to /usr/local/bin
  copy:
    src: '/tmp/composer.phar'
    dest: '/usr/local/bin/composer'
    mode: '0755'
