---
- name: Install PyCurl
  apt:
    name: python-pycurl
    state: present

- name: Include Debian Vars
  include_vars: Debian.yml

- name: Add Jenkins repository key
  apt_key:
    url: 'https://jenkins-ci.org/debian/jenkins-ci.org.key'
    state: present
    validate_certs: no

- name: Add Jenkins repository
  apt_repository:
    repo: 'deb http://pkg.jenkins-ci.org/debian binary/'
    state: present

- name: Install Java
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - 'openjdk-7-jre'
    - 'openjdk-7-jdk'

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Copy /etc/default/jenkins
  template:
    src: 'Debian/jenkins.j2'
    dest: '/etc/default/jenkins'

- name: Set Jenkins URL
  template:
    src: 'Debian/jenkins.model.JenkinsLocationConfiguration.xml.j2'
    dest: '/var/lib/jenkins/jenkins.model.JenkinsLocationConfiguration.xml'

- name: Restart Jenkins
  service:
    name: jenkins
    state: restarted

- name: Enable Jenkins
  service:
    name: jenkins
    enabled: yes
